const data = {
  products: [
    {
      name: "it shirts",
      category: "Shirts",
      image: "/images/shirt1.jpg ",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "cool shirts",
      category: "Shirts",
      image: "/images/shirt2.jpg ",
      price: 87,
      brand: "Adidas",
      rating: 4.7,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "slim shirts",
      category: "Shirts",
      image: "/images/shirt3.jpg ",
      price: 67,
      brand: "Nike",
      rating: 4.3,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "golf pants",
      category: "Pants",
      image: "/images/pants1.jpg ",
      price: 89,
      brand: "Oliver",
      rating: 4.8,
      numReviews: 10,
      countInStock: 20,
      description: "confort pants",
    },
    {
      name: "slim pants",
      category: "Pants",
      image: "/images/pants2.jpg ",
      price: 87,
      brand: "Zara",
      rating: 4.8,
      numReviews: 10,
      countInStock: 20,
      description: "popular pants",
    },
    {
      name: "jogging pants",
      category: "Shirts",
      image: "/images/pants3.jpg ",
      price: 75,
      brand: "Casely",
      rating: 4.8,
      numReviews: 10,
      countInStock: 20,
      description: "confort pants",
    },
  ],
};

export default data;
